[package]
name = "tokio_kcp"
version = "0.11.0"
authors = ["Matrix <113445886@qq.com>", "Y. T. Chung <zonyitoo@gmail.com>"]
description = "A kcp implementation for tokio"
license = "MIT"
readme = "README.md"
keywords = ["kcp", "udp", "reliable", "tokio"]
repository = "https://github.com/yeqiaojun/tokio_kcp"
edition = "2024"
rust-version = "1.85"

[dependencies]
byte_string = "1.0.0"
bytes = "1.12.1"
futures-util = "0.3.33"
kcp = "0.6.0"
log = "0.4.33"
rand = "0.8.7"
reed-solomon-erasure = "6.0.0"
spin = "0.9.9"
tokio = { version = "1.53.1", features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
env_logger = "0.11.11"
tokio = { version = "1.53.1", features = [
    "io-std",
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }
